### ISSUE TITLE
Moment uses 0 based index for month

### ISSUE THREAD

**Issue by tellingson** [ryanande/JsCombGuid#1]
I would recommend changing moment([1900, 1, 1]), "days") to moment([1900, 0, 1]), "days")

Currently it is using February 1st instead of January 1st.

It works as is as long as it is the only thing being used, but if you have multiple sources (SQL, C#, Javascript) generating the CombGuids, then it needs to be changed.

**Comment by ryanande** [comment]
Nice catch! Been awhile since I have looked at this code.
https://github.com/ryanande/JsCombGuid/pull/2
Merged.
